set(TOOLCHAIN_PREFIX /Applications/ArmGNUToolchain/12.2.mpacbti-bet1/arm-none-eabi/bin/arm-none-eabi-)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR            ${TOOLCHAIN_PREFIX}ar)
set(CMAKE_ASM_COMPILER  ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_C_COMPILER    ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER        ${TOOLCHAIN_PREFIX}ld)
set(CMAKE_OBJCOPY       ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "")
set(CMAKE_RANLIB        ${TOOLCHAIN_PREFIX}ranlib CACHE INTERNAL "")
set(CMAKE_SIZE          ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "")
set(CMAKE_STRIP         ${TOOLCHAIN_PREFIX}strip CACHE INTERNAL "")

set(CMAKE_C_FLAGS       "-Wno-psabi --specs=nosys.specs -fdata-sections -ffunction-sections -Wl,--gc-sections" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS     "${CMAKE_C_FLAGS} -fno-exceptions" CACHE INTERNAL "")

set(CMAKE_C_FLAGS_DEBUG             "-Os -g" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE           "-Os -DNDEBUG" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG           "${CMAKE_C_FLAGS_DEBUG}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELEASE         "${CMAKE_C_FLAGS_RELEASE}" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
